name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_test_publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t mathml-to-latex-publish .

      - name: Run Tests in Docker
        run: |
          docker run --rm mathml-to-latex-publish

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
