name: Test

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t mathml-to-latex-test .

      - name: Run Tests in Docker
        run: |
          docker run --rm mathml-to-latex-test
